# -*- coding: utf-8 -*-
"""calendar2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3wpkLcwI8dFpwA5YlXMWpnqvXAiNyg6

## Calendar2026_Project
"""

import sys
class CALENDAR2026:
  def __init__(self , month,dayno):
    try:
      self.month=month
      self.dayno=dayno
      self.days=["Thursday","Friday","Saturday","Sunday","Monday","Tuesday","Wednesday"]
      self.month_days={1: 31,2: 28,3: 31,4: 30,5: 31,6: 30,7: 31,8: 31,9: 30,10: 31,11: 30,12: 31 }
    except Exception as e:
      er_t,er_m,er_l = sys.exc_info()
      print(f"Error in Line no : {er_l.tb_lineno} : Reason  : {er_m} :due to {er_t}")

  def DAY_NAME(self):
     # Check month validity

    if self.month not in self.month_days:
      return "Invalid Month"
    elif (self.dayno <= 0) or (self.dayno > self.month_days[self.month]):
      return "Invalid date check date number"
    else:
      total_days= self.dayno
      for m in self.month_days:
        if m < self.month:
          total_days = total_days +self.month_days[m]
      index_day=((total_days -1) % 7)
      return f'{self.dayno} / {self.month} / 2026 is {self.days[index_day]}'
try:
  month = int(input("Enter Month Number (1-12): "))
  dayno = int(input("Enter Date: "))
except Exception as e:
      er_t,er_m,er_l = sys.exc_info()
      print(f"Error in Line no : {er_l.tb_lineno} : Reason  : {er_m} :due to {er_t}")
day_names = CALENDAR2026(month, dayno)
print(day_names.DAY_NAME())